root = "."
tmp_dir = "tmp"

[build]
  bin = "tmp/app"
  cmd = "go build -o ./tmp/app ."
  delay = 1000
  exclude_dir = ["tmp", "vendor"]
  rerun = true
  send_interrupt = true
  full_bin = "./tmp/app"
  send_interrupt = true

[log]
  color = "auto"
  time = true

[run]
  cmd = "./tmp/app"
